FROM rayproject/ray-ml:e23349-py39-gpu

WORKDIR /workspace

COPY ../requirements.txt .
RUN pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

# This is used for building vector store.
COPY ../contents ./contents
COPY ../pkg ./pkg
